### ISSUE TITLE
demo application crash

### ISSUE THREAD

**Issue by gilles-danjou** [ispikit/ispikit-cordova#2] opened 2016-03-15 13:11 UTC
Hi,

I've done the tutorial step by step. When I click the "start" button, the application crashes with the following log :

`io.cordova.hellocordova E/AndroidRuntime: FATAL EXCEPTION: Thread-402
                                                                       java.lang.NoSuchMethodError: org.json.JSONArray.<init>
                                                                           at com.ispikit.simplelibrary.SimpleIspikitWrapper.onNewAudio(SimpleIspikitWrapper.java:254)
                                                                           at dalvik.system.NativeStart.run(Native Method)`

Have an idea?

Thx

**Comment by gilles-danjou** [comment] 2016-03-15 13:12
I run the demo for android.

**Comment by gilles-danjou** [comment] 2016-03-15 14:34
It works on my Galaxy tab S2.

**Comment by syl22-00** [comment] 2016-03-15 18:58
Thanks @gilles-danjou for reporting. I have not been able to reproduce it on any of my environments, would you mind giving a few more details on where the issue happens: device or emulator? On which platform (Linux? Mac? Windows?)? What kind of image?

Also, as it seems to be an issue with the audio input, can you record audio with the device or emulator that exhibits the issue?

**Comment by gilles-danjou** [comment] 2016-03-16 15:05
@syl22-00, I run the applicaion on real devices : 

Samsung s7 (android 6.0.1) : not working (crash when I click on start)
Galaxy tab S2 - android 5.0.2 : working

**Comment by syl22-00** [comment] 2016-03-16 21:56
Thanks @gilles-danjou that was useful.

What happens is that on Android 6.0+, the way permissions work is slightly different. In addition to the permission requests in AndroidManifest.xml, the user needs to accept them one by one at runtime. So, on your Samsung S7, you can go to Settings - Apps - HelloCordova - Permissions and enable audio recording. The app should then work properly on your device.

I am not yet sure on how to have your app ask for that request on cordova, but with the Android SDK, our library shows how to do it (https://github.com/ispikit/ispikit-android).

So I am keeping this issue open until we include a proper way to have user accept the permissions when the app launches.

**Comment by gilles-danjou** [comment] 2016-03-18 11:16
You are right @syl22-00, when I activate "sound record" authorization, the app doesn't crash anymore.

I found [this plugin](https://www.npmjs.com/package/cordova-plugin-android-permissions) that should fix the bug (not tested yet).

**Comment by syl22-00** [comment] 2016-03-31 07:16
This was fixed by adding a modal to request for permissions on Android. Thanks for filing.

**Closed as completed by syl22-00** 2016-03-31 07:16 UTC
Labels: bug
